[2025-09-03T22:09:01.775+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: continuous_streaming_consumer.continuous_producer_consumer scheduled__2025-09-03T22:06:00+00:00 [queued]>
[2025-09-03T22:09:01.780+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: continuous_streaming_consumer.continuous_producer_consumer scheduled__2025-09-03T22:06:00+00:00 [queued]>
[2025-09-03T22:09:01.780+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-09-03T22:09:01.780+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1000
[2025-09-03T22:09:01.781+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-09-03T22:09:01.787+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): continuous_producer_consumer> on 2025-09-03 22:06:00+00:00
[2025-09-03T22:09:01.790+0000] {standard_task_runner.py:55} INFO - Started process 865 to run task
[2025-09-03T22:09:01.791+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'continuous_streaming_consumer', 'continuous_producer_consumer', 'scheduled__2025-09-03T22:06:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_continuous_consumer.py', '--cfg-path', '/tmp/tmpgz8b519d']
[2025-09-03T22:09:01.792+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask continuous_producer_consumer
[2025-09-03T22:09:01.801+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T22:09:01.813+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T22:09:01.832+0000] {task_command.py:388} INFO - Running <TaskInstance: continuous_streaming_consumer.continuous_producer_consumer scheduled__2025-09-03T22:06:00+00:00 [running]> on host 16d99b450999
[2025-09-03T22:09:01.872+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Klaus_Rezende
AIRFLOW_CTX_DAG_ID=continuous_streaming_consumer
AIRFLOW_CTX_TASK_ID=continuous_producer_consumer
AIRFLOW_CTX_EXECUTION_DATE=2025-09-03T22:06:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-09-03T22:06:00+00:00
[2025-09-03T22:09:01.876+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:09:01.876+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-09-03T22:09:01.877+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Connection complete.
[2025-09-03T22:09:01.880+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:09:01.880+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-09-03T22:09:01.880+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Connection complete.
[2025-09-03T22:09:01.978+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2025-09-03T22:09:01.978+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-09-03T22:09:01.982+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2025-09-03T22:09:01.982+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-09-03T22:09:01.983+0000] {consumer.py:118} WARNING - group_id is None: disabling auto-commit.
[2025-09-03T22:09:01.983+0000] {subscription_state.py:171} INFO - Updating subscribed topics to: ('streaming_data',)
[2025-09-03T22:09:01.984+0000] {subscription_state.py:257} INFO - Updated partition assignment: [('streaming_data', 0), ('streaming_data', 1), ('streaming_data', 2)]
[2025-09-03T22:09:01.984+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:09:01.985+0000] {conn.py:410} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Connection complete.
[2025-09-03T22:09:01.985+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. 
[2025-09-03T22:09:03.106+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:09:03.107+0000] {conn.py:410} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Connection complete.
[2025-09-03T22:09:03.107+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. 
[2025-09-03T22:09:03.111+0000] {logging_mixin.py:137} INFO - Produced post 1: sunt aut facere repellat provi...
[2025-09-03T22:09:03.114+0000] {logging_mixin.py:137} INFO - Consumed from partition 0, key 1: sunt aut facere repellat provi...
[2025-09-03T22:09:13.110+0000] {logging_mixin.py:137} INFO - Produced post 2: qui est esse...
[2025-09-03T22:09:13.114+0000] {logging_mixin.py:137} INFO - Consumed from partition 0, key 1: qui est esse...
[2025-09-03T22:09:23.124+0000] {logging_mixin.py:137} INFO - Produced post 3: ea molestias quasi exercitatio...
[2025-09-03T22:09:23.127+0000] {logging_mixin.py:137} INFO - Consumed from partition 0, key 1: ea molestias quasi exercitatio...
[2025-09-03T22:09:32.731+0000] {logging_mixin.py:137} INFO - Produced post 4: eum et est occaecati...
[2025-09-03T22:09:42.736+0000] {logging_mixin.py:137} INFO - Produced post 5: nesciunt quas odio...
[2025-09-03T22:09:52.741+0000] {logging_mixin.py:137} INFO - Produced post 6: dolorem eum magni eos aperiam ...
[2025-09-03T22:10:02.752+0000] {logging_mixin.py:137} INFO - Produced post 7: magnam facilis autem...
[2025-09-03T22:10:12.766+0000] {logging_mixin.py:137} INFO - Produced post 8: dolorem dolore est ipsam...
[2025-09-03T22:10:22.779+0000] {logging_mixin.py:137} INFO - Produced post 9: nesciunt iure omnis dolorem te...
[2025-09-03T22:10:32.791+0000] {logging_mixin.py:137} INFO - Produced post 10: optio molestias id quia eum...
[2025-09-03T22:10:42.815+0000] {logging_mixin.py:137} INFO - Produced post 11: et ea vero quia laudantium aut...
[2025-09-03T22:10:52.819+0000] {logging_mixin.py:137} INFO - Produced post 12: in quibusdam tempore odit est ...
[2025-09-03T22:11:02.827+0000] {logging_mixin.py:137} INFO - Produced post 13: dolorum ut in voluptas molliti...
[2025-09-03T22:11:12.841+0000] {logging_mixin.py:137} INFO - Produced post 14: voluptatem eligendi optio...
[2025-09-03T22:11:22.842+0000] {logging_mixin.py:137} INFO - Produced post 15: eveniet quod temporibus...
[2025-09-03T22:11:25.391+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connected> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: Socket EVENT_READ without in-flight-requests
[2025-09-03T22:11:25.392+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:25.443+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:25.443+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]> returned error 111. Disconnecting.
[2025-09-03T22:11:25.443+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T22:11:25.444+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:25.595+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:25.596+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]> returned error 111. Disconnecting.
[2025-09-03T22:11:25.596+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T22:11:25.596+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:25.848+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:25.848+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]> returned error 111. Disconnecting.
[2025-09-03T22:11:25.848+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T22:11:25.849+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-03T22:11:26.352+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: connecting to kafka:29092 [('172.16.240.7', 29092) IPv4]
[2025-09-03T22:11:26.353+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]> returned error 111. Disconnecting.
[2025-09-03T22:11:26.353+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.16.240.7', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-03T22:11:26.353+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
